<img src=https://i.ibb.co/6gCsHd6/1200px-Pandas-logo-svg.png width="700" height="200">

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

In [9]:
import numpy as np
import pandas as pd

In [10]:
labels = ['a', 'b', 'c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {'a': 10, 'b': 20, 'c': 30}

In [11]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [12]:
pd.Series([10, 20, 30])

0    10
1    20
2    30
dtype: int64

# Using NumPy Arrays


In [13]:
arr

array([10, 20, 30])

In [14]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [15]:
pd.Series(data=arr, index=labels)

a    10
b    20
c    30
dtype: int32

# Using Dictionaries

In [16]:
d

{'a': 10, 'b': 20, 'c': 30}

In [17]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

It used the dictionary keys as index. The keys of the dictionary match with the Index values; hence, the default Index values have no effect.

In [18]:
pd.Series(data=d, index=['q', 'c', 'y'])

q     NaN
c    30.0
y     NaN
dtype: float64

# Using Scalar Value

In [19]:
pd.Series(data="Steve")

0    Steve
dtype: object

In [20]:
pd.Series(data="Steve", index=range(3))

0    Steve
1    Steve
2    Steve
dtype: object

In [21]:
pd.Series(data = 10, index= ['a', 'b', 'c'])

a    10
b    10
c    10
dtype: int64

# Data in a Series

In [22]:
pd.Series([set, list, dict])

0     <class 'set'>
1    <class 'list'>
2    <class 'dict'>
dtype: object

In [23]:
pd.Series(set)[0]([2, 5, 7, 5, 8, 2])

{2, 5, 7, 8}

In [24]:
pd.Series([sum, print, len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [25]:
pd.Series([sum, print, len])[1]("a")

a


In [26]:
pd.Series([sum, print, len])[2]("clarusway")

9

In [27]:
mix_data = ['Aziz', 2, True]

In [28]:
ser = pd.Series(mix_data)
ser

0    Aziz
1       2
2    True
dtype: object

In [29]:
ser.dtype

dtype('O')

In [30]:
type(ser)

pandas.core.series.Series

In [31]:
type(ser[0])

str

In [32]:
type(ser[1])

int

In [33]:
arr = np.array(mix_data)
arr

array(['Aziz', '2', 'True'], dtype='<U4')

In [34]:
type(arr[2])

numpy.str_

# BASIC ATTRIBUTES & METHODS OF SERIES

**Series.dtype**	It returns the data type of the data.<br>
**Series.shape**	It returns a tuple of shape of the data.<br>
**Series.size**	    It returns the size of the data.<br>
**Series.ndim**	    It returns the number of dimensions in the data.<br>
**Series.index**	Defines the index of the Series.<br>
**Series.keys**  	Return alias for index.<br>
**Series.values**   Returns Series as ndarray or ndarray-like depending on the dtype.<br>
**Series.items**	Lazily iterate over (index, value) tuples.<br>
**Series.head**   	Return the first n rows.<br>
**Series.tail** 	Return the last n rows.<br>
**Series.sample**   Return a random sample of items from an axis of object.<br>
**Series.sort_index**  Sort Series by index labels.<br>
**Series.sort_values**  Sort by the values.<br>
**Series.isin**     Whether elements in Series are contained in values.<br>

In [35]:
ser = pd.Series(np.random.randint(0, 100, 7))
ser

0    78
1    65
2    55
3    30
4    44
5    45
6    98
dtype: int32

In [36]:
type(ser)

pandas.core.series.Series

In [37]:
ser.dtype

dtype('int32')

In [38]:
ser.shape

(7,)

In [39]:
ser.size

7

In [40]:
len(ser)

7

In [41]:
ser.ndim

1

In [42]:
ser

0    78
1    65
2    55
3    30
4    44
5    45
6    98
dtype: int32

In [43]:
ser.index

RangeIndex(start=0, stop=7, step=1)

In [45]:
ser.keys()

RangeIndex(start=0, stop=7, step=1)

In [46]:
list(ser.index) # we can also use "keys()" instead of "index"

[0, 1, 2, 3, 4, 5, 6]

In [38]:
for i in ser.index: # we can also use "keys()" instead of "index"
    print(i)

0
1
2
3
4
5
6


In [39]:
ser.values

array([55, 87, 85, 18, 45, 40, 12])

In [40]:
[i for i in ser.values]

[55, 87, 85, 18, 45, 40, 12]

In [41]:
for i in ser.values:
    print(i)

55
87
85
18
45
40
12


In [42]:
ser.items

<bound method Series.items of 0    55
1    87
2    85
3    18
4    45
5    40
6    12
dtype: int32>

In [43]:
ser.items()

In [44]:
list(ser.items())

[(0, 55), (1, 87), (2, 85), (3, 18), (4, 45), (5, 40), (6, 12)]

In [45]:
for index, value in ser.items():
    print(f"Index : {index}, Value : {value}")

Index : 0, Value : 55
Index : 1, Value : 87
Index : 2, Value : 85
Index : 3, Value : 18
Index : 4, Value : 45
Index : 5, Value : 40
Index : 6, Value : 12


In [46]:
ser = pd.Series(data = np.random.randint(0, 25, 10), index = [i for i in "cbaefdgihj"])

In [47]:
ser

c     9
b    21
a    16
e    16
f    14
d     1
g    24
i    14
h    20
j     6
dtype: int32

In [48]:
ser.head(3)

c     9
b    21
a    16
dtype: int32

In [49]:
ser.tail(2)

h    20
j     6
dtype: int32

In [50]:
ser.sample(2)

g    24
i    14
dtype: int32

In [51]:
ser.sort_index(ascending=True)

a    16
b    21
c     9
d     1
e    16
f    14
g    24
h    20
i    14
j     6
dtype: int32

In [52]:
ser.sort_values(ascending=False)

g    24
b    21
h    20
a    16
e    16
f    14
i    14
c     9
j     6
d     1
dtype: int32

In [53]:
ser

c     9
b    21
a    16
e    16
f    14
d     1
g    24
i    14
h    20
j     6
dtype: int32

In [54]:
ser.isin([5, 9])

c     True
b    False
a    False
e    False
f    False
d    False
g    False
i    False
h    False
j    False
dtype: bool

# Indexing and Slicing with Pandas Series

In [55]:
ser1 = pd.Series([1, 2, 3, 4], index = ['USA', 'Germany','RF', 'Japan'])
ser2 = pd.Series([1, 2, 5, 4, 6], index = ['USA', 'Germany','Italy', 'Japan', 'Spain'])

In [56]:
ser1

USA        1
Germany    2
RF         3
Japan      4
dtype: int64

In [57]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
Spain      6
dtype: int64

In [58]:
ser1.sort_index()

Germany    2
Japan      4
RF         3
USA        1
dtype: int64

In [59]:
ser2.sort_values()

USA        1
Germany    2
Japan      4
Italy      5
Spain      6
dtype: int64

In [60]:
ser1

USA        1
Germany    2
RF         3
Japan      4
dtype: int64

In [61]:
ser1[3]

4

In [62]:
ser1.index[3]

'Japan'

In [63]:
# pandas.index.get_loc
# index.get_loc(key, method=None, tolerance=None)[source]
# Get integer location, slice or boolean mask for requested label.

ser1.index.get_loc('Japan') 

3

In [64]:
ser1['Japan']

4

In [65]:
ser1.Japan

4

In [66]:
print("The value for 'Japan':", ser1['Japan'])

The value for 'Japan': 4


In [67]:
print("The value for the 3rd index:", ser1[3])

The value for the 3rd index: 4


In [68]:
# ser1[4]  # IndexError: index 4 is out of bounds for axis 0 with size 4

In [69]:
try:
    print("The value of the fourth element in the Series:", ser1[4])
except IndexError as error:
    print("Nope, the index you selected is out of bounds. That's not how you select rows (index) in a Series.")

Nope, the index you selected is out of bounds. That's not how you select rows (index) in a Series.


In [70]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
Spain      6
dtype: int64

In [71]:
ser2[0]

1

In [72]:
ser2[2:]

Italy    5
Japan    4
Spain    6
dtype: int64

In [73]:
ser2[::-1]

Spain      6
Japan      4
Italy      5
Germany    2
USA        1
dtype: int64

In [74]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
RF         NaN
Spain      NaN
USA        2.0
dtype: float64

In [75]:
ser1 * ser2

Germany     4.0
Italy       NaN
Japan      16.0
RF          NaN
Spain       NaN
USA         1.0
dtype: float64

In [76]:
ser = pd.Series(data = [121, 200, 150, 99], index = ["terry", "micheal", "orion", "jason"])
ser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [77]:
ser.index

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [78]:
ser['terry']

121

In [79]:
ser[0]

121

In [80]:
ser[[0,2]]

terry    121
orion    150
dtype: int64

In [81]:
ser[["terry", "orion"]]

terry    121
orion    150
dtype: int64

In [82]:
ser[0:3]

terry      121
micheal    200
orion      150
dtype: int64

In [83]:
ser['terry':'orion']

terry      121
micheal    200
orion      150
dtype: int64

# Selection with Condition and Broadcasting

In [84]:
ser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [85]:
'terry' in ser

True

In [86]:
'bob' in ser

False

In [87]:
121 in ser.values

True

In [88]:
55 in ser.values

False

In [89]:
ser < 100

terry      False
micheal    False
orion      False
jason       True
dtype: bool

In [90]:
ser[ser < 100] = 100
ser

terry      121
micheal    200
orion      150
jason      100
dtype: int64

In [91]:
ser.isin([121])

terry       True
micheal    False
orion      False
jason      False
dtype: bool

In [92]:
ser[ser.isin([121])] = 125
ser

terry      125
micheal    200
orion      150
jason      100
dtype: int64

# Recap for Selection

In [93]:
ser.keys()

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [94]:
ser.index

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [95]:
ser.values

array([125, 200, 150, 100], dtype=int64)

In [96]:
ser.items

<bound method Series.items of terry      125
micheal    200
orion      150
jason      100
dtype: int64>

In [97]:
ser.items()

In [98]:
list(ser.items())

[('terry', 125), ('micheal', 200), ('orion', 150), ('jason', 100)]

In [99]:
for index, value in ser.items():
    print(index, value)

terry 125
micheal 200
orion 150
jason 100


In [100]:
ser

terry      125
micheal    200
orion      150
jason      100
dtype: int64

In [101]:
ser.sort_index(ascending = False)

terry      125
orion      150
micheal    200
jason      100
dtype: int64

In [102]:
ser.sort_values(ascending = False)

micheal    200
orion      150
terry      125
jason      100
dtype: int64